name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4778ab934ecbd7e801684a4afa6f7bd530551b2475c7fc0241ae7ce4222ec97"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
