name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33f7f92dcc152342c7c427de21f067beae380f1a5f11384409a61b669c1eef3f"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
