name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23a71c6ee86ca00ee37b1602ef638c4a395bcae66eb85da8ae96b30a86c37ad9"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
