name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "933948f76ef91bb9ec06b65b9bbdc20d08668b9d14542c1dfc7711c6fe9b4e58"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
