name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c72dca56eb04fe181c92e0bceec8831b6033eacc8af1bf6c0dbc6be99e03b0fb"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
