name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ae99307c9db0e6ac963ec62d3811ac5470eb221bc4c46c416d0a3199e8a8a7b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
