name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2525398b8df6a3e3addbed1961ac45fc5d57a929116ef38587645ee612cef68b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
