name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb3ba0af6bc52de942e1b87315e748958bf3c97ebcfd681e2b573f2dc8907c11"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
