name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1fde0621477727eeea7bc96556d599c9367f6e20efc1c5816c6d9b7c7b63048"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
