name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03562372f4a5dfb151ea50d3ee3ba9c3f8d1d7b0f27bedde2c1d61a0fbedc3f0"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
