name = "Minecraft Thing"
author = "Octal!"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f45190806f31d7598f8ce2e511004d25b02af3f7a3623af82e78b372f08dcfb6"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
